# Generated by Django 4.1.4 on 2023-01-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balance",
            options={},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={},
        ),
        migrations.AlterModelOptions(
            name="profit",
            options={},
        ),
    ]
